# Generated by Django 6.0.6 on 2026-06-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_overallrecommendations_overallscorelevels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundingReference',
            fields=[
                ('id_grounding_reference', models.AutoField(primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=80, unique=True)),
                ('source_title', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('article', 'Scientific article'), ('framework', 'Framework or methodology'), ('standard', 'Standard or regulation'), ('report', 'Report or deliverable'), ('dataset', 'Dataset or extracted evidence'), ('internal', 'Internal RIAT note'), ('other', 'Other')], default='other', max_length=30)),
                ('citation', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('guidance', models.TextField(blank=True)),
                ('evidence_examples', models.TextField(blank=True)),
                ('applies_to_all_dimensions', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('retired', 'Retired')], default='draft', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimensions', models.ManyToManyField(blank=True, related_name='grounding_references', to='api.dimensions')),
            ],
            options={
                'db_table': 'grounding_references',
                'ordering': ['source_title'],
            },
        ),
    ]
